### ISSUE TITLE
在运行gazebo仿真时报错，无法启动gazebo:[spawner-2] [INFO] [1705993041.682129361] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist [spawner-2] [ERROR] [1705993043.689316324] [spawner_joint_state_broadcaster]: Controller manager not available

### ISSUE THREAD

**Issue by howe12** [AuboRobot/aubo_ros2_driver#2]
在运行gazebo仿真时报错，无法启动gazebo:
`[spawner-2] [INFO] [1705993041.682129361] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-2] [ERROR] [1705993043.689316324] [spawner_joint_state_broadcaster]: Controller manager not available
`
运行环境为：

> Ubuntu 22.04 

> ROS2 humble

运行过程如下：
```
cd aubo_ros_ws
colcon build
source install/setup.bash 
ros2 launch aubo_gazebo aubo_gazebo.launch.py aubo_type:=aubo_C3
```
详细报错信息如下：
```
[INFO] [launch]: All log files can be found below /home/nxrobo/.ros/log/2024-01-23-14-57-12-715311-nxrobo-8115
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [8117]
[INFO] [spawner-2]: process started with pid [8119]
[INFO] [gzserver-3]: process started with pid [8121]
[INFO] [gzclient-4]: process started with pid [8123]
[INFO] [spawn_entity.py-5]: process started with pid [8125]
[robot_state_publisher-1] [INFO] [1705993033.390139975] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1705993033.390272237] [robot_state_publisher]: got segment ee_link
[robot_state_publisher-1] [INFO] [1705993033.390277466] [robot_state_publisher]: got segment foreArm_Link
[robot_state_publisher-1] [INFO] [1705993033.390280966] [robot_state_publisher]: got segment shoulder_Link
[robot_state_publisher-1] [INFO] [1705993033.390284144] [robot_state_publisher]: got segment upperArm_Link
[robot_state_publisher-1] [INFO] [1705993033.390287193] [robot_state_publisher]: got segment world
[robot_state_publisher-1] [INFO] [1705993033.390290365] [robot_state_publisher]: got segment wrist1_Link
[robot_state_publisher-1] [INFO] [1705993033.390293717] [robot_state_publisher]: got segment wrist2_Link
[robot_state_publisher-1] [INFO] [1705993033.390296871] [robot_state_publisher]: got segment wrist3_Link
[spawn_entity.py-5] [INFO] [1705993033.718577544] [spawn_aubo]: Spawn Entity started
[spawn_entity.py-5] [INFO] [1705993033.718855900] [spawn_aubo]: Loading entity published on topic robot_description
[spawn_entity.py-5] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-5]   warnings.warn(
[spawn_entity.py-5] [INFO] [1705993033.720380333] [spawn_aubo]: Waiting for entity xml on robot_description
[spawn_entity.py-5] [INFO] [1705993033.731683022] [spawn_aubo]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-5] [INFO] [1705993033.732051820] [spawn_aubo]: Waiting for service /spawn_entity
[spawner-2] [INFO] [1705993035.660250141] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1705993037.667614298] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1705993039.674789575] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-2] [INFO] [1705993041.682129361] [spawner_joint_state_broadcaster]: Waiting for '/controller_manager' node to exist
[spawner-2] [ERROR] [1705993043.689316324] [spawner_joint_state_broadcaster]: Controller manager not available
[ERROR] [spawner-2]: process has died [pid 8119, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner joint_state_broadcaster --controller-manager /controller_manager --ros-args'].
[INFO] [rviz2-6]: process started with pid [8249]
[rviz2-6] [INFO] [1705993044.046291405] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-6] [INFO] [1705993044.046410505] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-6] [INFO] [1705993044.059861984] [rviz2]: Stereo is NOT SUPPORTED
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[rviz2-6] [INFO] [1705993060.940932310] [rclcpp]: signal_handler(signum=2)
[robot_state_publisher-1] [INFO] [1705993060.941044180] [rclcpp]: signal_handler(signum=2)
[spawn_entity.py-5] Traceback (most recent call last):
[spawn_entity.py-5]   File "/opt/ros/humble/lib/gazebo_ros/spawn_entity.py", line 370, in <module>
[spawn_entity.py-5]     main()
[spawn_entity.py-5]   File "/opt/ros/humble/lib/gazebo_ros/spawn_entity.py", line 365, in main
[spawn_entity.py-5]     exit_code = spawn_entity_node.run()
[spawn_entity.py-5]   File "/opt/ros/humble/lib/gazebo_ros/spawn_entity.py", line 228, in run
[spawn_entity.py-5]     success = self._spawn_entity(entity_xml, initial_pose, spawn_service_timeout)
[spawn_entity.py-5]   File "/opt/ros/humble/lib/gazebo_ros/spawn_entity.py", line 276, in _spawn_entity
[spawn_entity.py-5]     if client.wait_for_service(timeout_sec=timeout):
[spawn_entity.py-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/client.py", line 177, in wait_for_service
[spawn_entity.py-5]     time.sleep(sleep_time)
[spawn_entity.py-5] KeyboardInterrupt
[gzserver-3] [INFO] [1705993060.941127180] [rclcpp]: signal_handler(signum=2)
[ERROR] [gzclient-4]: process has died [pid 8123, exit code -2, cmd 'gzclient'].
[ERROR] [spawn_entity.py-5]: process has died [pid 8125, exit code -2, cmd '/opt/ros/humble/lib/gazebo_ros/spawn_entity.py -entity aubo -topic robot_description --ros-args -r __node:=spawn_aubo'].
[INFO] [robot_state_publisher-1]: process has finished cleanly [pid 8117]
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT) again, ignoring...
[gzserver-3] [INFO] [1705993061.116689749] [rclcpp]: signal_handler(signum=2)
[ERROR] [rviz2-6]: process has died [pid 8249, exit code -2, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d /home/nxrobo/aubo_ros_ws/install/aubo_description/share/aubo_description/rviz/view_robot.rviz --ros-args -r __node:=rviz2'].
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT) again, ignoring...
[gzserver-3] [INFO] [1705993061.277155712] [rclcpp]: signal_handler(signum=2)
[ERROR] [gzserver-3]: process[gzserver-3] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [gzserver-3]: sending signal 'SIGTERM' to process[gzserver-3]
[gzserver-3] [INFO] [1705993065.951643451] [rclcpp]: signal_handler(signum=15)
[ERROR] [gzserver-3]: process[gzserver-3] failed to terminate '10.0' seconds after receiving 'SIGTERM', escalating to 'SIGKILL'
[INFO] [gzserver-3]: sending signal 'SIGKILL' to process[gzserver-3]
[ERROR] [gzserver-3]: process has died [pid 8121, exit code -9, cmd 'gzserver -slibgazebo_ros_init.so -slibgazebo_ros_factory.so -slibgazebo_ros_force_system.so'].
```

我已安装以下功能包：
```
sudo apt install ros-humble-transmission-interface-*

sudo apt install ros-humble-gazebo-ros-control-*

sudo apt install ros-humble-joint-state-*

sudo apt install ros-humble-effort-controllers-*

sudo apt install ros-humble-position-controllers-*

sudo apt install ros-humble-control-manager-*
```
![image](https://github.com/AuboRobot/aubo_ros2_driver/assets/80575692/3659074e-ed1f-4a24-8fe9-b9d821193df8)

**Comment by kebiabc** [comment]
同样的情况，解决了吗

**Comment by jkxdl** [comment]
同样的情况，请问解决了吗

**Comment by JINGDU233** [comment]
同样的情况，请问解决了吗
